[book]
authors = ["Rahul Thakoor"]
multilingual = false
src = "src"
title = "Physical Computing with Rust"
description = "Use Rust to control LEDs, Buzzers, and more with the Raspberry Pi"

[build]
build-dir = "docs"

[output.html]
additional-css = ["asciinema-player.css"]
additional-js=["asciinema-player.js"]
google-analytics = "UA-118403602-3"