[book]
authors = ["Rahul Thakoor"]
multilingual = false
src = "src"
title = "Physical Computing with Rust"

[build]
build-dir = "docs"

[output.html]
additional-css = ["asciinema-player.css"]
additional-js=["asciinema-player.js"]